#! usr/bin/env python3.9

'''
───────────────────────────────────────
    #-named     = 表示名
    #-type      = アイテムのタイプ
    #-unity     = アイテムの大きな区分
    #-quantity  = 計算に使うための数字
    #-maxamount = 1スタックあたりの最大数
    #-energy    = エネルギー量[mj]
───────────────────────────────────────
'''
#----all items description below
items= {

#----ores
    'iron ore': {
        'named'     : '鉄鉱石',
        'type tag'  : ('ore deposit', 'ores'),  #--鉱床
        'unity'     : 'raw material', #--未加工鉱物
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
        },
    'copper ore': {
        'named'     : '銅鉱石',
        'type tag'  : ('ore deposit', 'ores'),
        'unity'     : 'raw material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
        },
    'caterium ore': {
        'named'     : 'カテリウム鉱石',
        'type tag'  : ('ore deposit', 'ores'),
        'unity'     : 'raw material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
        },
    'coal': {
        'named'     : '石炭',
        'type tag'  : ('ore deposit', 'ores', 'fuels'),
        'unity'     : 'raw material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 300,
        },
    'raw quartz': {
        'named'     : '未加工石英',
        'type tag'  : ('ore deposit', 'ores'),
        'unity'     : 'raw material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
        },
    'limestone': {
        'named'     : '石灰石',
        'type tag'  : ('ore deposit', 'ores'),
        'unity'     : 'raw material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
        },
    'sulfur': {
        'named'     : '硫黄',
        'type tag'  : ('ore deposit', 'ores'),
        'unity'     : 'raw material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
        },
    'bauxite': {
        'named'     : 'ボーキサイト',
        'type tag'  : ('ore deposit', 'ores'),
        'unity'     : 'raw material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
        },
    'uranium': {
        'named'     : 'ウラン',
        'type tag'  : ('ore deposit', 'ores'),
        'unity'     : 'raw material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
        },
    's.a.m. ore': {
        'named'     : 's.a.m.鉱石',
        'type tag'  : ('ore deposit', 'ores'),
        'unity'     : 'in dev',     #--開発段階(?)のため、本編未使用のものの部類
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
        },
#----ingots
    'iron ingot':{
        'named'     : '鉄のインゴット',
        'type tag'  : ('component', 'ingots'),    #--未加工の資源を製錬、精製、または加工したもの
        'unity'     : 'material',     #--一般的な意味での材料
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'copper ingot':{
        'named'     : '銅のインゴット',
        'type tag'  : ('component', 'ingots'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'caterium ingot': {
        'named'     : 'カテリウムのインゴット',
        'type tag'  : ('component', 'ingots'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'steel ingot':    {
        'named'     : '鋼鉄のインゴット',
        'type tag'  : ('component', 'ingots'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'aluminum ingot': {
        'named'     : 'アルミのインゴット',
        'type tag'  : ('component', 'ingots'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },

#----minerals
    'concrete': {
        'named'     : 'コンクリート',
        'type tag'  : ('component', 'minerals'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },   
    'quartz crystal': {
        'named'     : '石英結晶',
        'type tag'  : ('component', 'minerals'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },   
    'silica': {
        'named'     : 'シリカ',
        'type tag'  : ('component', 'minerals'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },   
    'copper powder': {
        'named'     : '銅粉',
        'type tag'  : ('component', 'minerals'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },   
    'polymer resin': {
        'named'     : '合成樹脂',
        'type tag'  : ('component', 'minerals'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },   
    'petroleum coke': {
        'named'     : '石油コークス',
        'type tag'  : ('component', 'minerals', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 180,
    },   
    'aluminum scrap': {
        'named'     : 'アルミのスクラップ',
        'type tag'  : ('component', 'minerals'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
#----aliens
    'alien protein': {
        'named'     : 'エイリアンのタンパク質',
        'type tag'  : ('alien', 'aliens'),      #--異星生物関連
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'alien dna capsule': {
        'named'     : 'エイリアンのdnaカプセル',
        'type tag'  : ('alien', 'aliens'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },

#----liquids
    'water ': {
        'named'     : '水',
        'type tag'  : ('liquid', 'liquids'),   #--液体類
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 1,
        'energy'    : 0,
    },
    'crude oil': {
        'named'     : '原油',
        'type tag'  : ('liquid', 'liquids', 'fuels'),
        'unity'     : 'raw material',
        'quantity'  : 1,
        'max amount': 1,
        'energy'    : 0.32,
    },
    'heavy oil residue': {
        'named'     : '重廃油',
        'type tag'  : ('liquid', 'liquids', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 1,
        'energy'    : 0.4,
    },
    'fuel': {
        'named'     : '燃料',
        'type tag'  : ('liquid', 'liquids', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 1,
        'energy'    : 0.75,
    },
    'liquid biofuel': {
        'named'     : '液体バイオ燃料',
        'type tag'  : ('liquid', 'liquids', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 1,
        'energy'    : 0.75,
    },
    'turbofuel': {
        'named'     : 'ターボ燃料',
        'type tag'  : ('liquid', 'liquids', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 1,
        'energy'    : 2,
    },
    'alumina solution': {
        'named'     : 'アルミナ溶液',
        'type tag'  : ('liquid', 'liquids'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 1,
        'energy'    : 0,
    },
    'sulfuric acid': {
        'named'     : '硫酸',
        'type tag'  : ('liquid', 'liquids'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 1,
        'energy'    : 0,
    },
    'nitric acid': {
        'named'     : '硝酸',
        'type tag'  : ('liquid', 'liquids'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 1,
        'energy'    : 0,
    },
#----gas
    'nitrogen gas': {
        'named'     : '窒素ガス',
        'type tag'  : ('gas', 'nomary gas'),     #--気体類
        'unity'     : 'raw material',
        'quantity'  : 1,
        'max amount': 1,
        'energy'    : 0,
    },
#----standard parts
    'iron rod': {
        'named'     : '鉄のロッド',
        'type tag'  : ('parts', 'standard parts'),    #--基本的にインゴットを加工して得られる基礎部品
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'screw': {
        'named'     : 'ネジ',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
    'iron plate': {
        'named'     : '鉄板',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'reinforced iron plate': {
        'named'     : '強化鉄板',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'copper sheet': {
        'named'     : '銅のシート',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'alclad aluminum sheet': {
        'named'     : 'アルクラッド・アルミシート',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'aluminum casing': {
        'named'     : 'アルミ筐体',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'steel pipe': {
        'named'     : '鋼鉄のパイプ',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'steel beam': {
        'named'     : '鋼梁',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'encased industrial beam': {
        'named'     : 'コンクリート被覆型鋼梁',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'modular frame': {
        'named'     : 'モジュラー・フレーム',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'heavy modular frame': {
        'named'     : 'ヘビー・モジュラー・フレーム',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'fused modular frame': {
        'named'     : '溶融モジュラー・フレーム',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'fabric': {
        'named'     : '布地',
        'type tag'  : ('parts', 'standard parts', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 15,
    },
    'plastic': {
        'named'     : 'プラスチック',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'rubber': {
        'named'     : 'ゴム',
        'type tag'  : ('parts', 'standard parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
#----industrial parts
    'rotor': {
        'named'     : 'ローター',
        'type tag'  : ('parts', 'industrial parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'stator': {
        'named'     : '固定子',
        'type tag'  : ('parts', 'industrial parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'battery': {
        'named'     : 'バッテリー',
        'type tag'  : ('parts', 'industrial parts', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 6000,
    },
    'motor': {
        'named'     : 'モーター',
        'type tag'  : ('parts', 'industrial parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'heat sink': {
        'named'     : 'ヒートシンク',
        'type tag'  : ('parts', 'industrial parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'cooling system': {
        'named'     : '冷却システム',
        'type tag'  : ('parts', 'industrial parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'turbo motor': {
        'named'     : 'ターボモーター',
        'type tag'  : ('parts', 'industrial parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
#----electronics
    'wire': {
        'named'     : 'ワイヤー',
        'type tag'  : ('parts', 'electronics'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
    'cable': {
        'named'     : 'ケーブル',
        'type tag'  : ('parts', 'electronics'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'quickwire': {
        'named'     : 'クイックワイヤー',
        'type tag'  : ('parts', 'electronics'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
    'circuit board': {
        'named'     : '回路基板',
        'type tag'  : ('parts', 'electronics'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'ai limiter': {
        'named'     : 'aiリミッター',
        'type tag'  : ('parts', 'electronics'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'high-speed connector': {
        'named'     : '高速コネクター',
        'type tag'  : ('parts', 'electronics'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
#----communications
    'computer': {
        'named'     : 'コンピューター',
        'type tag'  : ('parts', 'communications'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'supercomputer': {
        'named'     : 'スーパーコンピューター',
        'type tag'  : ('parts', 'communications'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'quantum computer': {
        'named'     : '量子コンピューター',
        'type tag'  : ('parts', 'communications'),
        'unity'     : 'in dev',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'radio control unit': {
        'named'     : '無線制御ユニット',
        'type tag'  : ('parts', 'communications'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'crystal oscillator': {
        'named'     : '水晶発振器',
        'type tag'  : ('parts', 'communications'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'superposition oscillator': {
        'named'     : '重ね合わせ発振器',
        'type tag'  : ('parts', 'communications'),
        'unity'     : 'in dev',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
#----containers
    'empty canister': {
        'named'     : '空の容器',
        'type tag'  : ('container', 'containers'),    #--容器関係
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'empty fluid tank': {
        'named'     : '空の液体タンク',
        'type tag'  : ('container', 'liquid containers'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'pressure conversion cube': {
        'named'     : '圧力変換キューブ',
        'type tag'  : ('container', 'containers'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'packaged water': {
        'named'     : '容器入り水',
        'type tag'  : ('container', 'liquid containers'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'packaged alumina solution': {
        'named'     : '容器入りアルミナ溶液',
        'type tag'  : ('container', 'liquid containers'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'packaged sulfuric acid': {
        'named'     : '容器入り硫酸',
        'type tag'  : ('container', 'liquid containers'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'packaged nitric acid': {
        'named'     : '容器入り硝酸',
        'type tag'  : ('container', 'liquid containers'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'packaged nitrogen gas': {
        'named'     : '容器入り窒素ガス',
        'type tag'  : ('container', 'gas containers'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
#----fuels
    'leaves': {
        'named'     : '葉',
        'type tag'  : ('biomass', 'fuels'),    #--バイオマス関連
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 15,
    },
    'mycelia': {
        'named'     : '菌糸',
        'type tag'  : ('biomass', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 20,
    },
    'flower petals': {
        'named'     : '花弁',
        'type tag'  : ('special', 'fuels'),     #--パーツでも材料でもない特殊枠
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 100,
    },
    'wood': {
        'named'     : '木',
        'type tag'  : ('biomass', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 100,
    },
    'biomass': {
        'named'     : 'バイオマス',
        'type tag'  : ('biomass', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 180,
    },
    'compacted coal': {
        'named'     : '圧縮石炭',
        'type tag'  : ('component', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 630,
    },
    'packaged oil': {
        'named'     : '容器入り原油',
        'type tag'  : ('container','fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 320,
    },
    'packaged heavy oil residue': {
        'named'     : '容器入り廃重油',
        'type tag'  : ('container','fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 400,
    },
    'solid biofuel': {
        'named'     : '個体バイオ燃料',
        'type tag'  : ('biomass', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 450,
    },
    'packaged fuel': {
        'named'     : '容器入り燃料',
        'type tag'  : ('container','fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 750,
    },
    'packaged liquid biofuel': {
        'named'     : '容器入り液体バイオ燃料',
        'type tag'  : ('container','fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 750,
    },
    'packaged turbofuel': {
        'named'     : '容器入りターボ燃料',
        'type tag'  : ('container','fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 2000,
    },
    'uranium fuel rod': {
        'named'     : 'ウラン燃料棒',
        'type tag'  : ('component', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 750000,
    },
    'plutonium fuel rod': {
        'named'     : 'プルトニウム燃料棒',
        'type tag'  : ('component', 'fuels'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 1500000,
    },
#----consumed
    'black powder': {
        'named'     : '黒色火薬',
        'type tag'  : ('explosive', 'consumed'),   #--消耗品類
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'smokeless powder': {
        'named'     : '無煙火薬',
        'type tag'  : ('explosive', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'gas filter': {
        'named'     : 'ガスフィルター',
        'type tag'  : ('filter', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'color cartridge': {
        'named'     : 'カラー弾薬',
        'type tag'  : ('consumed', 'fuels'), 
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 900,
    },
    'beacon': {
        'named'     : 'ビーコン',
        'type tag'  : ('beacon', 'consumed'),
        'unity'     : 'in dev',   #将来のアップデートで消される可能性あり
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'iodine infused filter': {
        'named'     : 'ヨウ素充填フィルター',
        'type tag'  : ('filter', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
#----ammos
    'iron rebar': {
        'named'     : '鉄筋',
        'type tag'  : ('ammos', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'stun rebar': {
        'named'     : 'スタン鉄筋',
        'type tag'  : ('ammos', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'shatter rebar': {
        'named'     : '破砕鉄筋',
        'type tag'  : ('ammos', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'explosive rebar': {
        'named'     : '爆砕鉄筋',
        'type tag'  : ('ammos', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'rifle ammo': {
        'named'     : 'ライフル弾',
        'type tag'  : ('ammos', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
    'homing rifle ammo': {
        'named'     : 'ホーミングライフル弾',
        'type tag'  : ('ammos', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
    'turbo rifle ammo': {
        'named'     : 'ターボライフル弾',
        'type tag'  : ('ammos', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
    'nobelisk': {
        'named'     : 'ノーべリスク',
        'type tag'  : ('bomb', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'gas nobelisk': {
        'named'     : 'ガス・ノーべリスク',
        'type tag'  : ('bomb', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'pulse nobelisk': {
        'named'     : 'パルス・ノーべリスク',
        'type tag'  : ('bomb', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'cluster nobelisk': {
        'named'     : 'クラスター・ノーべリスク',
        'type tag'  : ('bomb', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'nuke nobelisk': {
        'named'     : 'ニューク・ノーべリスク',
        'type tag'  : ('bomb', 'consumed'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
#----nuclear
    'electromagnetic control rod': {
        'named'     : '電磁制御棒',
        'type tag'  : ('parts', 'nuclear'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'encased uranium cell': {
        'named'     : '被覆型ウラン・セル',
        'type tag'  : ('parts', 'nuclear'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
    'non-fissile uranium': {
        'named'     : '非分裂製ウラン',
        'type tag'  : ('parts', 'nuclear'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
    'plutonium pellet': {
        'named'     : 'プルトニウム・ペレット',
        'type tag'  : ('parts', 'nuclear'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'encased plutonium cell': {
        'named'     : '被覆型プルトニウム・セル',
        'type tag'  : ('parts', 'nuclear'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 200,
        'energy'    : 0,
    },
#----waste
    'uranium waste': {
        'named'     : 'ウラン廃棄物',
        'type tag'  : ('parts', 'waste', 'nuclear'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
    'plutonium waste': {
        'named'     : 'プルトニウム廃棄物',
        'type tag'  : ('parts', 'waste', 'nuclear'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
#----special
    'blue power slug': {
        'named'     : '青いパワー・スラッグ',
        'type tag'  : ('special', 'power slug'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'yellow power slug': {
        'named'     : '黄色いパワー・スラッグ',
        'type tag'  : ('special', 'power slug'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'purple power slug': {
        'named'     : '紫のパワー・スラッグ',
        'type tag'  : ('special', 'power slug'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'power shard': {
        'named'     : 'パワー・シャード',
        'type tag'  : ('special',),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 100,
        'energy'    : 0,
    },
    'ficsit coupon': {
        'named'     : 'ficsitクーポン',
        'type tag'  : ('special',),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 500,
        'energy'    : 0,
    },
    'smart plating': {
        'named'     : 'スマート・プレート',
        'type tag'  : ('special',),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'versatile framework': {
        'named'     : '多目的フレームワーク',
        'type tag'  : ('special', 'parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'automated wiring': {
        'named'     : '自動ワイヤー',
        'type tag'  : ('special', 'parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'modular engine': {
        'named'     : 'モジュラーエンジン',
        'type tag'  : ('special', 'parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'adaptive control unit': {
        'named'     : '自律制御ユニット',
        'type tag'  : ('special', 'parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'assembly director system': {
        'named'     : '組立指揮システム',
        'type tag'  : ('special', 'parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'magnetic field generator': {
        'named'     : '磁界発生装置',
        'type tag'  : ('special', 'parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'thermal propulsion rocket': {
        'named'     : '熱推進型ロケット',
        'type tag'  : ('special', 'parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
    },
    'nuclear pasta': {
        'named'     : '核パスタ',
        'type tag'  : ('special', 'parts'),
        'unity'     : 'material',
        'quantity'  : 1,
        'max amount': 50,
        'energy'    : 0,
        'recipe'    : ()
    },
}